ALTER TABLE deals DROP CONSTRAINT IF EXISTS deals_status_check;

ALTER TABLE deals ADD CONSTRAINT deals_status_check
    CHECK (status IN ('PENDING', 'CONFIRMED', 'PAYMENT_PENDING', 'PAID', 'ACTIVE', 'COMPLETED', 'REJECTED', 'CANCELLED'));